spring.application.name=watchlist
spring.datasource.url=jdbc:postgresql://localhost:5432/animewatchlistdb
spring.datasource.username=postgres
spring.datasource.password=Nzbf@1968


spring.jpa.hibernate.ddl-auto=update